version: '3.8'
services:
  db:
    image: postgres:15
    container_name: time-track-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: time_track
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: time-track-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/time_track

  frontend:
    build: ./frontend
    container_name: time-track-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
